name: Sunya
title: Sunya
description: Your personal cloud, in space
baseurl: ""

gtag_id: G-K7180BMVP5

cancel_policy: Cancel within 30 days and get your money back, no questions asked
preorder_cancel_policy: Cancel your preorder anytime and get your money back, no questions asked

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap # keep this last

products:
  folio:
    yearly_price_usd: 12
    subscribe_url: https://buy.stripe.com/6oU3cvd4tdfYeIjbok0Ba0i
  news:
    yearly_price_usd: 24
    subscribe_url: https://buy.stripe.com/fZuaEXd4tek243F1NK0Ba0h
  universe_news_and_folio:
    yearly_price_usd: 32
    subscribe_url: https://buy.stripe.com/00wcN5fcBa3Mbw7gIE0Ba0j
  analytics_sublight:
    yearly_price_usd: 50
    subscribe_url: https://buy.stripe.com/3cI6oH1lLfo6gQr0JG0Ba0k
  links_light:
    yearly_price_usd: 6
    subscribe_url: https://buy.stripe.com/dRmdR90hH1xg1VxfEA0Ba0l
